SWP\ContentBundle\Document\Article:
    referenceable: true
    parentdocument: parent
    nodename: title
    id: id
    fields:
        content:
            type: string
        slug:
            type: string
    referenceOne:
        route:
            targetDocument: "\\SWP\\ContentBundle\\Document\\Route"
            strategy: hard
