SWP\ContentBundle\Document\Article:
    repositoryClass: SWP\ContentBundle\Document\ArticleRepository
    referenceable: true
    id:
        fieldName: id
        generator:
            strategy: repository
    fields:
        title:
            type: string
        content:
            type: string
        slug:
            type: string
    referenceOne:
        route:
            targetDocument: "\\Symfony\\Cmf\\Bundle\\RoutingBundle\\Doctrine\\Phpcr\\Route"
            strategy: hard
