services:
    swp_renderer.phpcr.initializer:
         class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
         arguments:
             - Default initializer
             - [ "%swp_multi_tenancy.persistence.phpcr.basepath%" ]
         tags:
             - { name: "doctrine_phpcr.initializer", priority: 100 }

# override default cmf dynamic router with our implementation (with support for Meta Article)
parameters:
    cmf_routing.dynamic_router.class: SWP\WebRendererBundle\Routing\MetaRouter
