imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    swp_multi_tenancy.tenant.class: SWP\MultiTenancyBundle\Model\TenantInterface

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        name: SUPERDESKWEBPUBLISHER
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    strict_variables: false

liip_theme:
    themes: ['theme_1', 'theme_2', 'theme_3']
    active_theme: "%active_theme%"
    load_controllers: false
    autodetect_theme: true
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%current_device%%/%%template%%
            - %%app_path%%/views/%%current_device%%/%%template%%

twig_cache:
    service: doctrine_cache.providers.doctrine.orm.default_metadata_cache

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        resolve_target_entities:
            SWP\MultiTenancyBundle\Model\TenantInterface: %swp_multi_tenancy.tenant.class%
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                mappings:
                    SWPContentBundle:
                        type: yml
                        prefix: "SWP\ContentBundle\Model"
                        dir: Resources/config/doctrine
                    SWPMultiTenancyBundle:
                        type: yml
                        prefix: "SWP\MultiTenancyBundle\Model"
                        dir: Resources/config/doctrine
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    soft-deleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                    tenantable:
                        class: SWP\MultiTenancyBundle\Query\Filter\TenantableFilter
                        enabled: true
doctrine_cache:
    providers:
        metadata_chain:
            chain:
                providers:
                    #- metadata_redis
                    - metadata_array
        metadata_array:
            type: array
            namespace: swp_metadata
        metadata_redis:
            type: redis
            namespace: swp_metadata
        nodes_chain:
            chain:
                providers:
                    #- nodes_redis
                    - nodes_array
        nodes_array:
            type: array
            namespace: swp_nodes
        nodes_redis:
            type: redis
            namespace: swp_nodes

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_http_cache: ~

doctrine_phpcr:
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"
    session:
        backend:
            type: doctrinedbal
            caches:
                meta: doctrine_cache.providers.metadata_chain
                nodes: doctrine_cache.providers.nodes_chain
            logging: true
            profiling: true
        workspace: default

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        route_collection_limit: 100
        persistence:
            phpcr:
                enabled: true
                route_basepaths: "/swp/routes"

oneup_flysystem:
    adapters:
        swp_local:
            local:
                directory: %kernel.root_dir%/Resources/uploads

    filesystems:
        my_filesystem:
            adapter: swp_local

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
        view_response_listener: 'force'
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

sensio_framework_extra:
    view:    { annotations: false }

swp_updater:
    version_class: %swp_updater.version.class%
    client:
        base_uri: http://updates.sourcefabric.org

swp_bridge:
    base_uri: 'http://superdesk.dev:5050'

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            softdeleteable: true
            loggable: true

swp_multi_tenancy:
    persistence:
        phpcr:
            enabled: true
            rootpath: "/swp/"
            content_paths: %swp_multi_tenancy.phpcr.contentpaths%
