swp_webrenderer:
    resource: "@SWPWebRendererBundle/Controller/"
    type:     annotation

swp_updater:
    resource: "@SWPUpdaterBundle/Resources/config/routing.yml"

swp_bridge:
    resource: "@SWPBridgeBundle/Resources/config/routing.yml"
