services:
    swp_template_engine.loader.article:
        class: SWP\ContentBundle\Loader\ArticleLoader
        arguments:
            - %kernel.root_dir%
            - @doctrine_phpcr.odm.document_manager
            - @doctrine.orm.entity_manager
        tags:
            - { name: swp.meta_loader }

    document_manager:
        alias: doctrine_phpcr.odm.document_manager
